# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-19 23:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Automotores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CUIL', models.CharField(max_length=100)),
                ('MATRICULA', models.CharField(max_length=100)),
                ('MATRICULA_ANTERIOR', models.CharField(max_length=100)),
                ('MARCA', models.CharField(max_length=100)),
                ('MODELO', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Comercio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('COMERCIO_ID', models.CharField(max_length=100)),
                ('NOMBRE_FANTASIA', models.CharField(max_length=100)),
                ('DOMICILIO_COMERCIO', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DatosComunes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NOMBRE_APELLIDO', models.CharField(max_length=100)),
                ('FECHA_NACIMIENTO', models.DateField(null=True)),
                ('TIPO_DOCUMENTO', models.CharField(max_length=20)),
                ('NUMERO_DOCUMENTO', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='DatosEspecificos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DESCRIPCION', models.CharField(max_length=100)),
                ('FECHA_IMPORTACION', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Domicilio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CALLE', models.CharField(max_length=100)),
                ('NUMERO', models.CharField(max_length=60)),
                ('PISO', models.CharField(max_length=60)),
                ('DEPARTAMENTO', models.CharField(max_length=60)),
                ('LOCALIDAD', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Padrones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NOMBREPADRON', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DESCRIPCION', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('USUARIO', models.CharField(max_length=255, unique=True)),
                ('NOMBRE_APELLIDO', models.CharField(max_length=255)),
                ('DNI', models.CharField(max_length=12, unique=True)),
                ('active', models.BooleanField(default=True)),
                ('staff', models.BooleanField(default=False)),
                ('admin', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='domicilio',
            name='PADRON',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PBI.Padrones'),
        ),
        migrations.AddField(
            model_name='domicilio',
            name='PERSONA',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PBI.DatosComunes'),
        ),
        migrations.AddField(
            model_name='datosespecificos',
            name='PADRON',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PBI.Padrones'),
        ),
        migrations.AddField(
            model_name='datosespecificos',
            name='PERSONA',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PBI.DatosComunes'),
        ),
        migrations.AddField(
            model_name='datosespecificos',
            name='TIPO_DATO',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PBI.Tipo'),
        ),
        migrations.AddField(
            model_name='comercio',
            name='PERSONA',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PBI.DatosComunes'),
        ),
        migrations.AddField(
            model_name='automotores',
            name='PERSONA',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PBI.DatosComunes'),
        ),
    ]
