# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-20 00:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PBI', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='DNI',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='NOMBRE_APELLIDO',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
